version: '3.7'

services:

    redis:
        image: redis
        container_name: redis

    db:
        image: postgres
        container_name: db
        env_file:
            - .env-non-dev
        ports:
            - 5432:5432
        volumes:
            - postgresdata:/var/lib/postgresql/data

    app:
        build:
            context: .
        container_name: app
        ports:
            - 8000:8000
        depends_on:
            - redis
            - db
        command: sh -c "alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"

    celery:
        image: booking_celery
        build:
            context: . # celery это библиотека, у неё нет образа, берём из основного билда
        container_name: booking_celery
        command: sh -c "celery --app=app.tasks.celery:celery worker -l INFO"
        env_file:
            - .env-non-dev
        depends_on:
            - redis

volumes:
    postgresdata:
